spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-store
    username: rayhan
    password: rayhan123
  application:
    name: spring-store
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
  security:
    user:
      name: rayhan
      password: rayhan123