spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-store
    username: rayhan
    password: rayhan123
  application:
    name: spring-store
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

payment:
  gateway: paypal